### ISSUE TITLE
Request: Exclude Character from commands checkbox

### ISSUE THREAD

**Issue by majorcyto** [GiR-Zippo/HypnotoadUi#1]
Hi,

I play with 9 accounts, 8 are my bards and 1 is my main that I use to run around and talk to the crowd with. I know some people use even more accounts, like 4 to shoot fireworks with macros.

On the character list, can we have a check mark to skip receiving commands for certain characters, and can this also include skipping the party invite command. Currently it never fails that it will invite 7 of my bard accounts, and then my main and i have to manually leave the bard party and have the bard leader account invite the other bard account to the party.

If it is possible to put this in, it would be super appreciated!

**Comment by majorcyto** [comment]
@GiR-Zippo - It didn't auto assign you, and im not sure if it sent you a notification. Tagged you, just in case!

**Comment by GiR-Zippo** [comment]
Will take some time to implement this... but should be possible.

**Comment by GiR-Zippo** [comment]
And it's done via BC Enable checkbox

**Comment by majorcyto** [comment]
Thank you so much!
