### ISSUE TITLE
Can we also get the /hbrn command that allows broadcasting the command to everyone but me.

### ISSUE THREAD

**Issue by majorcyto** [GiR-Zippo/HypnotoadUi#2]
Hi, In BTB there is 2 versions of this command, the one we have now and the one that broadcasts the command to all clients except yourself. Can we please get this version of the command as well, this will fix my remaining macros haha. :P

**Comment by majorcyto** [comment]
@GiR-Zippo does this tag you automatically, or do I need to do this? xD

**Comment by GiR-Zippo** [comment]
We already have the two versions /hbr and /hbrn :P

https://github.com/GiR-Zippo/HypnotoadUi/blob/main/HypnotoadUi/Commands.cs

**Comment by majorcyto** [comment]
haha I just realized this today that those macros were actually working already, my bad! Sorry
